# Generated by Django 3.0.2 on 2020-06-08 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_pizza_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='toppings',
        ),
    ]
